### ISSUE TITLE
Where the hell is README.md

### ISSUE THREAD

**Issue by architect-711** [stinger222/qr-code-generator#1]
Так как вы обозначены, как **contributor** проекта Игоря Глинка _DontationExecutor_, полагаю вы говорите по-русски. И так, я изучил ваш профиль и обнаружил этот весьма занимательный проект. И у меня встал вопрос, а где **README**? 

Как же можно понять, какие технологии используются, как это выполняется.
Как кодер кодеру, советую почитать статью, о том как делать **README** файлы
https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

**Comment by paveldayo** [comment]
@architect-711, Спасибо)) я как раз сейчас вылизываю проекты что-бы они красиво смотрелись в портфолио, а readme я планировал написать в последнюю очередь. Eсли говорить про конкретно этот проектик, то его тоже скоро ждёт рефактор, а там уже и readme

_и спасибо за статейку_
